# Generated by Django 2.1.7 on 2019-02-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20190221_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='message',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
